import { Folder, Trash2 } from "lucide-solid";
import type {
  CleanupRiskProfile,
  CleanupRiskProfileKey,
  MonorepoMode,
  NavItem,
  PlanCategory,
  PlanItem,
  ProjectSnapshot,
  ScanRoot,
  SettingsTabItem,
  ThemeKey,
  ThemePresetKey,
  ThemeVars,
} from "./types";

export const navItems: NavItem[] = [
  { key: "manage", label: "项目概览", icon: Folder },
  { key: "cleanup", label: "清理", icon: Trash2 },
];

export const monorepoModeOptions: Array<{ value: MonorepoMode; label: string }> = [
  { value: "repoRootOnly", label: "仅仓库根目录" },
  { value: "packagesOnly", label: "仅工作区子包" },
  { value: "both", label: "根目录与子包" },
];

export const themeOptions: Array<{ key: ThemeKey; label: string; description: string }> = [
  { key: "system", label: "跟随系统", description: "跟随系统的浅色或深色模式" },
  { key: "white", label: "纯白", description: "明亮干净，适合白天使用" },
  { key: "black", label: "纯黑", description: "更沉静，适合长时间查看" },
  { key: "current", label: "暖砂", description: "柔和暖色，层次更轻一些" },
  { key: "lavender", label: "薰衣草", description: "偏冷的浅色界面，观感更柔和" },
  { key: "custom", label: "自定义", description: "按自己的习惯调整颜色和细节" },
];

export const settingsTabs: SettingsTabItem[] = [
  {
    key: "appearance",
    label: "外观",
    description: "主题、颜色和界面细节",
  },
  {
    key: "scan",
    label: "扫描",
    description: "管理扫描目录和项目显示",
  },
  {
    key: "cleanup",
    label: "清理",
    description: "设置默认清理方式和自动清理",
  },
];

export const themeBadgeLabels: Record<ThemeKey, string> = {
  system: "系统",
  current: "暖砂",
  white: "纯白",
  black: "纯黑",
  lavender: "薰衣草",
  custom: "自定义",
};

export const planCategoryLabels: Record<PlanCategory, string> = {
  cache: "缓存",
  build: "构建产物",
  report: "测试覆盖率",
  temp: "临时文件",
};

export const defaultCleanupRiskProfile: CleanupRiskProfile = {
  cache: "low",
  build: "low",
  report: "low",
  temp: "low",
  dependencies: "medium",
  rustTarget: "low",
};

export const cleanupRiskProfileFieldLabels: Record<CleanupRiskProfileKey, string> = {
  cache: "缓存目录（如 .cache、.turbo、.next/cache）",
  build: "构建目录（如 dist、build、out、.next）",
  report: "覆盖率目录（coverage）",
  temp: "临时目录（tmp、temp）",
  dependencies: "依赖目录（node_modules）",
  rustTarget: "Rust 构建目录（target）",
};

export const cleanupRiskProfileFields: CleanupRiskProfileKey[] = [
  "cache",
  "build",
  "report",
  "temp",
  "dependencies",
  "rustTarget",
];

const sharedThemeTokens: ThemeVars = {
  "--space-1": "4px",
  "--space-2": "8px",
  "--space-3": "12px",
  "--space-4": "16px",
  "--space-5": "20px",
  "--space-6": "24px",
  "--space-7": "32px",
  "--radius-lg": "10px",
  "--radius-md": "8px",
  "--radius-sm": "6px",
  "--titlebar-height": "36px",
  "--transition": "180ms ease",
  "--shadow": "none",
};

export const themePresets: Record<ThemePresetKey, ThemeVars> = {
  current: {
    ...sharedThemeTokens,
    "--bg": "#f6eee8",
    "--bg-tint": "#efe2d8",
    "--panel": "#fff8f2",
    "--panel-soft": "#f7ede3",
    "--line": "#e6d5c8",
    "--line-strong": "#d8c1b0",
    "--text-strong": "#402a22",
    "--text-normal": "#64493d",
    "--text-muted": "#8a6c5f",
    "--primary": "#c68e72",
    "--primary-hover": "#b37d63",
    "--primary-soft": "rgba(198, 142, 114, 0.16)",
    "--primary-outline": "rgba(198, 142, 114, 0.38)",
    "--success": "#6f9a7a",
    "--warning": "#b0794f",
  },
  white: {
    ...sharedThemeTokens,
    "--bg": "#ffffff",
    "--bg-tint": "#f6f7f9",
    "--panel": "#ffffff",
    "--panel-soft": "#fafbfc",
    "--line": "#e3e7ee",
    "--line-strong": "#d0d7e2",
    "--text-strong": "#111827",
    "--text-normal": "#374151",
    "--text-muted": "#6b7280",
    "--primary": "#1f64c7",
    "--primary-hover": "#1a53a3",
    "--primary-soft": "rgba(31, 100, 199, 0.08)",
    "--primary-outline": "rgba(31, 100, 199, 0.32)",
    "--success": "#217a4b",
    "--warning": "#9f6015",
    "--shadow": "0 18px 34px -28px rgba(17, 24, 39, 0.2)",
  },
  black: {
    ...sharedThemeTokens,
    "--bg": "#0c0f12",
    "--bg-tint": "#12161c",
    "--panel": "#171c23",
    "--panel-soft": "#1d242d",
    "--line": "#2b3440",
    "--line-strong": "#3a4756",
    "--text-strong": "#f3f4f6",
    "--text-normal": "#d5dae1",
    "--text-muted": "#9aa5b3",
    "--primary": "#4e8eea",
    "--primary-hover": "#3b78cf",
    "--primary-soft": "rgba(78, 142, 234, 0.14)",
    "--primary-outline": "rgba(78, 142, 234, 0.35)",
    "--success": "#33a26a",
    "--warning": "#d98a2b",
    "--shadow": "0 22px 42px -28px rgba(0, 0, 0, 0.85)",
  },
  lavender: {
    ...sharedThemeTokens,
    "--bg": "#f7f3ff",
    "--bg-tint": "#ede5ff",
    "--panel": "#fcf9ff",
    "--panel-soft": "#f4edff",
    "--line": "#ddcff4",
    "--line-strong": "#c8b4e8",
    "--text-strong": "#2f2345",
    "--text-normal": "#4f3f70",
    "--text-muted": "#7f6f9f",
    "--primary": "#7b5cc9",
    "--primary-hover": "#694ab5",
    "--primary-soft": "rgba(123, 92, 201, 0.12)",
    "--primary-outline": "rgba(123, 92, 201, 0.34)",
    "--success": "#3d8b72",
    "--warning": "#ad7a29",
    "--shadow": "0 18px 36px -28px rgba(68, 47, 120, 0.42)",
  },
};

export const projectSnapshots: ProjectSnapshot[] = [
  {
    id: "northstar",
    name: "northstar-console",
    path: "~/Code/northstar-console",
    packageManagers: ["bun", "cargo"],
    reclaimableGb: 4.2,
    inactiveDays: 3,
    kind: "repo-root",
    profile: "前端 Monorepo",
    technology: {
      languages: ["TypeScript", "Rust"],
      frameworks: ["Solid", "Tauri"],
      buildTools: ["Vite"],
      commandRunner: "Bun",
    },
    workspaceRole: "仓库根目录",
    workspaceUnits: 6,
    startupCommands: [
      { label: "前端开发", command: "bun run dev" },
      { label: "桌面调试", command: "bun run tauri dev" },
      { label: "构建产物", command: "bun run build && bun run tauri build" },
    ],
  },
  {
    id: "atlas-web",
    name: "@atlas/web",
    path: "~/Code/atlas/apps/web",
    packageManagers: ["bun"],
    reclaimableGb: 1.8,
    inactiveDays: 12,
    kind: "package",
    profile: "前端工作区子包",
    technology: {
      languages: ["TypeScript"],
      frameworks: ["React"],
      buildTools: ["Vite"],
      commandRunner: "Bun",
    },
    workspaceRole: "monorepo 子包",
    workspaceUnits: 1,
    startupCommands: [
      { label: "本地开发", command: "bun run dev" },
      { label: "生产构建", command: "bun run build" },
    ],
  },
  {
    id: "atlas-api",
    name: "@atlas/api",
    path: "~/Code/atlas/apps/api",
    packageManagers: ["pnpm"],
    reclaimableGb: 2.4,
    inactiveDays: 24,
    kind: "package",
    profile: "服务端子包",
    technology: {
      languages: ["TypeScript"],
      frameworks: [],
      buildTools: [],
      commandRunner: "pnpm",
    },
    workspaceRole: "monorepo 子包",
    workspaceUnits: 1,
    startupCommands: [
      { label: "本地开发", command: "pnpm dev" },
      { label: "构建", command: "pnpm build" },
      { label: "启动", command: "pnpm start" },
    ],
  },
  {
    id: "pixel-note",
    name: "pixel-note",
    path: "~/Work/pixel-note",
    packageManagers: ["npm"],
    reclaimableGb: 0.9,
    inactiveDays: 56,
    kind: "single",
    profile: "独立前端项目",
    technology: {
      languages: ["TypeScript"],
      frameworks: ["Solid"],
      buildTools: ["Vite"],
      commandRunner: "npm",
    },
    workspaceRole: "单项目",
    workspaceUnits: 1,
    startupCommands: [
      { label: "本地开发", command: "npm run dev" },
      { label: "构建", command: "npm run build" },
      { label: "预览", command: "npm run preview" },
    ],
  },
];

export const initialScanRoots: ScanRoot[] = [
  { path: "~/Code", depth: 4 },
  { path: "~/Work", depth: 3 },
  { path: "/Volumes/Archive/Projects", depth: 2 },
];

export const cleanupPlanByProject: Record<string, PlanItem[]> = {
  northstar: [
    {
      id: "northstar-next-cache",
      label: "Next 缓存",
      relativePath: ".next/cache",
      sizeGb: 1.7,
      risk: "low",
      category: "cache",
      impact: "下次启动需重新生成 Next 编译缓存",
      recommended: true,
    },
    {
      id: "northstar-turbo",
      label: "Turbo 工作区缓存",
      relativePath: ".turbo",
      sizeGb: 1.1,
      risk: "low",
      category: "cache",
      impact: "首次任务图计算会变慢，后续恢复正常",
      recommended: true,
    },
    {
      id: "northstar-dist",
      label: "构建产物",
      relativePath: "dist",
      sizeGb: 1.4,
      risk: "low",
      category: "build",
      impact: "发布包会被移除，重新构建即可恢复",
      recommended: true,
    },
  ],
  "atlas-web": [
    {
      id: "atlas-web-vite",
      label: "Vite 转换缓存",
      relativePath: ".vite",
      sizeGb: 0.6,
      risk: "low",
      category: "cache",
      impact: "依赖预构建缓存会重建，首开稍慢",
      recommended: true,
    },
    {
      id: "atlas-web-coverage",
      label: "覆盖率报告",
      relativePath: "coverage",
      sizeGb: 0.3,
      risk: "low",
      category: "report",
      impact: "历史覆盖率报告将清空，不影响运行",
      recommended: false,
    },
    {
      id: "atlas-web-cache",
      label: "node_modules 缓存",
      relativePath: "node_modules/.cache",
      sizeGb: 0.9,
      risk: "medium",
      category: "cache",
      impact: "下次安装与构建时间会明显增加",
      recommended: false,
    },
  ],
  "atlas-api": [
    {
      id: "atlas-api-ts",
      label: "TypeScript 增量缓存",
      relativePath: "*.tsbuildinfo",
      sizeGb: 0.2,
      risk: "low",
      category: "cache",
      impact: "首次类型检查会重新全量编译",
      recommended: true,
    },
    {
      id: "atlas-api-dist",
      label: "构建产物",
      relativePath: "dist",
      sizeGb: 1.6,
      risk: "low",
      category: "build",
      impact: "部署产物会被清空，需要重新构建",
      recommended: true,
    },
    {
      id: "atlas-api-eslint",
      label: "ESLint 缓存",
      relativePath: ".eslintcache",
      sizeGb: 0.1,
      risk: "low",
      category: "temp",
      impact: "下次 lint 会重新扫描全部文件",
      recommended: true,
    },
  ],
  "pixel-note": [
    {
      id: "pixel-note-parcel",
      label: "Parcel 缓存",
      relativePath: ".parcel-cache",
      sizeGb: 0.2,
      risk: "low",
      category: "cache",
      impact: "打包缓存将重建，首次启动变慢",
      recommended: true,
    },
    {
      id: "pixel-note-build",
      label: "构建产物",
      relativePath: "build",
      sizeGb: 0.7,
      risk: "low",
      category: "build",
      impact: "静态发布目录会清空，需重新构建",
      recommended: true,
    },
  ],
};
